-- MySQL Script generated by MySQL Workbench
-- Thu Jul 13 01:40:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema poll.io
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `poll.io` ;

-- -----------------------------------------------------
-- Schema poll.io
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poll.io` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `poll.io` ;

-- -----------------------------------------------------
-- Table `poll.io`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll.io`.`User` ;

CREATE TABLE IF NOT EXISTS `poll.io`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `PasswordHash` VARCHAR(512) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poll.io`.`Poll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll.io`.`Poll` ;

CREATE TABLE IF NOT EXISTS `poll.io`.`Poll` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Key` VARCHAR(45) NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `Key_UNIQUE` (`Key` ASC),
  INDEX `PollUserID_idx` (`UserID` ASC),
  CONSTRAINT `PollUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `poll.io`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poll.io`.`QuestionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll.io`.`QuestionType` ;

CREATE TABLE IF NOT EXISTS `poll.io`.`QuestionType` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poll.io`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll.io`.`Question` ;

CREATE TABLE IF NOT EXISTS `poll.io`.`Question` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  `QuestionTypeID` INT NOT NULL,
  `PollID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `QuestionPollID_idx` (`PollID` ASC),
  INDEX `QuestionTypeID_idx` (`QuestionTypeID` ASC),
  CONSTRAINT `QuestionPollID`
    FOREIGN KEY (`PollID`)
    REFERENCES `poll.io`.`Poll` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `QuestionTypeID`
    FOREIGN KEY (`QuestionTypeID`)
    REFERENCES `poll.io`.`QuestionType` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poll.io`.`QuestionChoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll.io`.`QuestionChoice` ;

CREATE TABLE IF NOT EXISTS `poll.io`.`QuestionChoice` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QuestionID` INT NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `ChoiceQuestionID_idx` (`QuestionID` ASC),
  CONSTRAINT `ChoiceQuestionID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `poll.io`.`Question` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poll.io`.`Response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll.io`.`Response` ;

CREATE TABLE IF NOT EXISTS `poll.io`.`Response` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QuestionID` INT NOT NULL,
  `ResponseContent` BLOB NULL,
  `QuestionChoiceID` INT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `UserID_idx` (`UserID` ASC),
  INDEX `ResponseQuestionID_idx` (`QuestionID` ASC),
  INDEX `ResponseChoiceID_idx` (`QuestionChoiceID` ASC),
  CONSTRAINT `ResponseUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `poll.io`.`User` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ResponseQuestionID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `poll.io`.`Question` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ResponseChoiceID`
    FOREIGN KEY (`QuestionChoiceID`)
    REFERENCES `poll.io`.`QuestionChoice` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
